apiVersion: v1
kind: Config
clusters:
    - name: k8s-basic-cluster
      cluster:
          server: https://k8s-basic-cluster.zeet.app
          certificate-authority-data: <INSERT_CERTIFICATE_AUTHORITY_DATA_HERE>
contexts:
    - name: default-context
      context:
          cluster: k8s-basic-cluster
          namespace: default
          user: default-user
current-context: default-context
users:
    - name: default-user
      user:
          token: <INSERT_SERVICE_ACCOUNT_TOKEN_HERE>
